@extends('adminlte::page')
@section('title', 'SIEBDATA')
@section('plugins.Datatables', true)
@section('plugins.Select2', true)
@section('plugins.JQuery', true)
@section('plugins.Sweetalert2', true)
@include('right-sidebar')
@section('content_header')
    @yield('contenido')
@stop